### ISSUE TITLE
Suggestion: use `undefined` instead of `null` to signal rejection

### ISSUE THREAD

**Issue by erikkemperman** [gulpjs/value-or-function#8]
I have a feeling I might have suggested this before, sorry if I am repeating myself here...

Having `undefined` as a special coercer type seems a bit meaningless to me, as it would have only a single valid value. My feeling is it's currently only in there to complete the list of primitive types.

At the same time, `null` strikes me as a perfectly reasonably value for `object` type values, but is currently not allowed (or more precisely, indistinguishable from rejection).

So would it make sense to change the semantics of the return value?

If so, something like the following commit would do the trick (this on top of the PR I just opened, but should be pretty easy to untangle):
https://github.com/erikkemperman/value-or-function/commit/5202fc298d390a55afeb42babea2e94512e2af94

**Comment by phated** [comment]
I'm fine with removing `undefined` support but I'd want everything to be accept null/undefined interchangeably (using `!= null` or `== null`).

**Comment by erikkemperman** [comment]
I think the return type for rejected `normalize` should be strictly `undefined` -- to facilitate the case with `'object'` type I mentioned... I suppose the semantics of custom coercer return values can be more lenient, if that's what you mean?

**Comment by phated** [comment]
I actually don't think that `null` is a desirable result for the built-in `object` coercer

**Comment by erikkemperman** [comment]
Sorry if I'm being unclear -- its late here and I really need some sleep... I'm thinking the built-in object coercer should return the value if `typeof val === 'object'` (so that would include `null` as acceptable input for this type) and otherwise signal rejection with `undefined`. Does that make sense?

**Comment by phated** [comment]
Yeah, I understand you but that, in my opinion, is bad/incorrect behavior of the language.  In the context of this library, `object` is going to be used as a "plain object" type and `null` should **not** pass validation.

**Comment by erikkemperman** [comment]
Interesting! I guess I had not been thinking of this library -- and certainly the primitive built-ins -- as doing _validation_ beyond attempting basic type coercion...

So basically, I would expect for all the primitive types, that if I do `result = normalize(type, value)` then the result is either rejection (`undefined`) or otherwise I can safely assume that `typeof result === type`.

At present this is true for all primitive types -- except `'object'`, which was the point of this proposal. Notice that even `normalize('number', Number.NaN)` is accepted -- which I think makes sense, because `typeof Number.NaN === 'number'`. We actually test this case [here](https://github.com/gulpjs/value-or-function/blob/master/test/index.js#L211).

And so yes, I would actually like to be able to pass in `null` and have it accepted (because `typeof null === 'object'`). That might be just me though :-) To make "room", i.e. reserve a value that unambiguously signals rejection, I thought `undefined` was the obvious candidate. But that doesn't work without removing that builtin coercer -- which didn't strike me as a big loss because it only ever accepts a single value.

**Comment by phated** [comment]
Thanks for the detailed explanation. 😄   I merged the PR I submitted so I think this is wrapped up.

**Comment by phated** [comment]
Closed by 4c4ff01e00af1b5c2b3322cb8e3f131b18fc27af
